id: I8A47F77D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:11:14+00:00'
last_modified: '2022-06-16T06:19:07.395528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ20864
  title: ལུས་ཐིག་ཟླ་བ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3D3D:
      image_group_id: I1KG14375
      title: ''
      total_pages: 256
      order: 1
      base_file: 3D3D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
